#!/bin/sh
# Autostart Programs.
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
pgrep -x nm-applet > /dev/null || nm-applet &
feh --bg-scale $HOME/.config/bspwm/wallpaper.jpg
picom -f &

# Monitors.
bspc monitor -d I II III IV V VI VII VIII

# Gaps and Borders.
bspc config border_width         2
bspc config window_gap          12

# Focus.
bspc config focus_follows_pointer	true
bspc config history_aware_focus         true

# Colors.
bspc config focused_border_color	"#e6b31e"
bspc config focused_sticky_border_color	"#25C0EF"
bspc config normal_sticky_border_color	"#468395"
bspc config active_sticky_border_color	"#468395"
bspc config normal_border_color		"#07617d"
bspc config presel_border_color		yellow
bspc config urgent_border_color		red
bspc config borderless_monocle		true
bspc config gapless_monocle		true

# Misc.
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Bind applications to Workspaces.
bspc rule -a Termite desktop='^1' follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on
bspc rule -a zoom desktop='^4' follow=on
bscp rule -a TelegramDesktop desktop='^5' follow=on
bscp rule -a vlc desktop='^6' follow=on
bscp rule -a Virt-manager desktop='^7' follow=on
bsco rule -a Code desktop='^8' follow=on

# Floating.
bspc rule -a "Galculator" state=floating
bspc rule -a "Pavucontrol" state=floating

# Use monocle on Desktops.
bspc desktop '^2' --layout monocle
bspc desktop '^4' --layout monocle
bspc desktop '^6' --layout monocle
bspc desktop '^7' --layout monocle
bspc desktop '^8' --layout monocle
